{{ config(
    materialized = 'incremental',
    unique_key = 'CD_AGENDAMENTO'
)}}

SELECT
	DISTINCT {{ dbt_utils.generate_surrogate_key(['POSSUI_AGENDA_PLANO','MOTIVO_AGENDA_PLANO']) }} AS CD_AGENDAMENTO,
	POSSUI_AGENDA_PLANO AS DS_MOTIVO_COMPLETO,
	MOTIVO_AGENDA_PLANO AS DS_MOTIVO,
	CASE
		WHEN SUBSTR(POSSUI_AGENDA_PLANO, 1, 3) = 'SIM' THEN 1
		ELSE 0
	END AS FG_AGENDAMENTO,
	substr(POSSUI_AGENDA_PLANO, 1, 3) AS DS_AGENDA_PLANO
FROM
	APP_GESTAO_REDE.ST_CLIENTE_OCULTO sco

-- SELECT 
--     c8_ds_NAO_AGENDAMENTO AS DS_MOTIVO_COMPLETO,
-- 	SUBSTR(c8_ds_NAO_AGENDAMENTO,7) AS DS_MOTIVO,
-- 	CASE WHEN SUBSTR(c8_ds_NAO_AGENDAMENTO,1, 3) = 'SIM' THEN 1 ELSE 0 END AS FG_AGENDAMENTO,
--     substr(c8_ds_NAO_AGENDAMENTO, 1, 3) AS DS_AGENDA_PLANO
    
-- FROM {{source('APP_GESTAO_REDE','ST_LISTAS_CLIENTE_OCULTO')}}