{{ config(
    materialized = 'incremental',
    unique_key = ['CD_TENTATIVA','CD_UNIMED','CD_CICLO_PESQUISA', 'CD_PRESTADOR', 'CD_ENDERECO', 'NR_TENTATIVAS'],
    post_hook=[
        create_index_safe(
            index_name='IDX_TF_PRESTADOR_CICLO',
            table_name=this,
            columns=['CD_TENTATIVA','CD_UNIMED','CD_CICLO_PESQUISA', 'CD_PRESTADOR', 'CD_ENDERECO','NR_TENTATIVAS']
        )
    ]
)}}

WITH CTE AS (
    SELECT
        CP.CD_CICLO_PESQUISA,
		CASE WHEN CO.TENTATIVA_1_DATA_HORA <> TIMESTAMP '0001-01-01 00:00:00.000000' THEN CO.TENTATIVA_1_DATA_HORA ELSE NULL END AS DT_TENTATIVA_1,
        CASE WHEN CO.TENTATIVA_2_DATA_HORA <> TIMESTAMP '0001-01-01 00:00:00.000000' THEN CO.TENTATIVA_2_DATA_HORA ELSE NULL END AS DT_TENTATIVA_2,
        CASE WHEN CO.TENTATIVA_3_DATA_HORA <> TIMESTAMP '0001-01-01 00:00:00.000000' THEN CO.TENTATIVA_3_DATA_HORA ELSE NULL END  AS DT_TENTATIVA_3,
        CASE
            WHEN CO.TENTATIVA_3_DATA_HORA IS NOT NULL AND CO.TENTATIVA_3_DATA_HORA <> TIMESTAMP '0001-01-01 00:00:00.000000' THEN 3
            WHEN CO.TENTATIVA_2_DATA_HORA IS NOT NULL AND CO.TENTATIVA_2_DATA_HORA <> TIMESTAMP '0001-01-01 00:00:00.000000' THEN 2
            WHEN CO.TENTATIVA_1_DATA_HORA IS NOT NULL AND CO.TENTATIVA_1_DATA_HORA <> TIMESTAMP '0001-01-01 00:00:00.000000' THEN 1
        END AS NR_TENTATIVAS,
        CO.DATA_CONTATO AS DT_CONTATO,
        CASE
            WHEN CO.DATA_AGENDA_PRESTADOR = '01/01/0001' THEN NULL
            ELSE CO.DATA_AGENDA_PRESTADOR
        END AS DT_AGENDA,
        CASE WHEN CO.RESTRICAO_IDADE = 'SIM' THEN 1 WHEN CO.RESTRICAO_IDADE = 'NÃO' THEN 0 END AS FG_RESTRICAO_IDADE,
        CASE WHEN CO.RESTRICAO_IDADE = 'SIM' THEN CO.QUAL_RESTRICAO END AS DS_RESTRICAO,
        CASE WHEN CO.GINECOLOGISTA_PRE_NATAL = 'SIM' THEN 1 WHEN CO.GINECOLOGISTA_PRE_NATAL = 'NÃO' THEN 0 END AS FG_PRE_NATAL,
        CASE WHEN CO.POSSUI_AGENDA_PARTICULAR = 'SIM' THEN 1 WHEN CO.POSSUI_AGENDA_PARTICULAR = 'NÃO' THEN 0 END AS FG_AGENDA_PARTICULAR,
        CASE WHEN CO.POSSUI_AGENDA_PARTICULAR = 'SIM' THEN CO.DATA_CONSULTA_PARTICULAR END AS DT_CONSULTA_PARTICULAR,
        CASE
            WHEN CO.VALOR_CONSULTA_PARTICULAR LIKE '%NÃO INFORMADO%' THEN NULL
            ELSE CO.VALOR_CONSULTA_PARTICULAR
        END AS NR_VALOR_CONSULTA_PARTICULAR,
        CASE WHEN CO.NR_CHAMADO_MOVIDESK IS NOT NULL THEN 1 ELSE 0 END AS FG_CHAMADO_MOVIDESK,
        CO.NR_CHAMADO_MOVIDESK,
        P.CD_PRESTADOR,
--        MA.CD_AGENDAMENTO,
        SUBSTR(CO.UNIMED_AREA_ACAO, 1, INSTR(CO.UNIMED_AREA_ACAO, ' ') - 1) AS CD_UNIMED,
--        CONT.CD_CONTATO,
       ST.CD_TENTATIVA,
        ENDE.CD_ENDERECO
    FROM {{source('APP_GESTAO_REDE','ST_CLIENTE_OCULTO')}} CO
        LEFT JOIN {{ ref('td_ciclo_pesquisa')}} CP ON CP.DS_CICLO_PESQUISA = UPPER(CO.CICLO_PESQUISA)
        LEFT JOIN {{ ref('td_endereco')}} ENDE ON CO.MUNICIPIO = ENDE.DS_MUNICIPIO AND
									    CO.BAIRRO = ENDE.DS_BAIRRO AND
									    CO.CEP = ENDE.CD_CEP AND
									    NVL(CO.UF,0) = NVL(ENDE.CD_UF,0) AND
									    CO.ENDERECO = ENDE.DS_RUA AND
									    CO.NUMERO = ENDE.NR_NUMERO
        LEFT JOIN {{ ref('td_prestador')}} P ON UPPER(CO.NOME_RAZAO_SOCIAL) = UPPER(P.DS_RAZAO_SOCIAL)
                                 AND ENDE.CD_ENDERECO = P.CD_ENDERECO
                                 AND P.CD_RNP = CO.CD_PRESTADOR_RNP
                                 AND P.DS_CICLO_PESQUISA = UPPER(CO.CICLO_PESQUISA)
                                 AND P.telefone_01 = co.telefone_01


        -- LEFT JOIN {{ ref('td_motivo_agendamento')}} MA ON MA.DS_MOTIVO_COMPLETO = CO.POSSUI_AGENDA_PLANO AND NVL(MA.DS_MOTIVO, 'SEM_VALOR') = NVL(CO.MOTIVO_AGENDA_PLANO, 'SEM_VALOR')
--        LEFT JOIN {{ ref('td_contato')}} CONT ON CONT.DS_CONTATO = CO.MOTIVOS_FALTA_CONTATO
       LEFT JOIN {{ ref('td_status_tentativa')}} ST ON ST.DS_STATUS_TENTATIVA = CO.STATUS_TENTATIVA
        where CO.CICLO_PESQUISA IS NOT NULL 
)

, EA_DIAS_PLANO (CD_PRESTADOR, DT_CONTATO, DT_AGENDA, EACHDATE) AS (
    SELECT CD_PRESTADOR, DT_CONTATO, DT_AGENDA, DT_CONTATO AS EACHDATE FROM CTE
    UNION ALL
    SELECT CD_PRESTADOR, DT_CONTATO, DT_AGENDA, EACHDATE + 1 FROM EA_DIAS_PLANO
    WHERE DT_AGENDA IS NOT NULL AND EACHDATE < DT_AGENDA
)

, DIAS_PLANO AS (
    SELECT
        PD.CD_PRESTADOR,
        PD.DT_CONTATO,
        PD.DT_AGENDA,
        SUM(CASE WHEN TO_CHAR(PD.EACHDATE, 'DY', 'NLS_DATE_LANGUAGE=PORTUGUESE') NOT IN ('SÁB', 'DOM') 
                 AND F.DT_FERIADOS IS NULL THEN 1 ELSE 0 END) AS NR_DIAS_ESPERA_PLANO
    FROM EA_DIAS_PLANO PD
        LEFT JOIN FERIADOS F ON F.DT_FERIADOS = PD.EACHDATE
    WHERE PD.DT_AGENDA IS NOT NULL
    GROUP BY PD.CD_PRESTADOR, PD.DT_CONTATO, PD.DT_AGENDA
)

, EA_DIAS_PARTICULAR (CD_PRESTADOR, DT_CONTATO, DT_CONSULTA_PARTICULAR, EACHDATE) AS (
    SELECT CD_PRESTADOR, DT_CONTATO, DT_CONSULTA_PARTICULAR, DT_CONTATO AS EACHDATE FROM CTE WHERE DT_CONSULTA_PARTICULAR IS NOT NULL
    UNION ALL
    SELECT CD_PRESTADOR, DT_CONTATO, DT_CONSULTA_PARTICULAR, EACHDATE + 1 FROM EA_DIAS_PARTICULAR
    WHERE EACHDATE < DT_CONSULTA_PARTICULAR
)

, DIAS_PARTICULAR AS (
    SELECT
        PD.CD_PRESTADOR,
        PD.DT_CONTATO,
        PD.DT_CONSULTA_PARTICULAR,
        SUM(CASE WHEN TO_CHAR(PD.EACHDATE, 'DY', 'NLS_DATE_LANGUAGE=PORTUGUESE') NOT IN ('SÁB', 'DOM') 
                 AND F.DT_FERIADOS IS NULL THEN 1 ELSE 0 END) AS NR_DIAS_ESPERA_PARTICULAR
    FROM EA_DIAS_PARTICULAR PD
        LEFT JOIN FERIADOS F ON F.DT_FERIADOS = PD.EACHDATE
    WHERE PD.DT_CONSULTA_PARTICULAR IS NOT NULL
    GROUP BY PD.CD_PRESTADOR, PD.DT_CONTATO, PD.DT_CONSULTA_PARTICULAR
)

SELECT 
    CTE.CD_PRESTADOR,
    CTE.CD_CICLO_PESQUISA,
    CTE.NR_TENTATIVAS,
    CTE.DT_CONTATO,
	CTE.DT_TENTATIVA_1,
    CTE.DT_TENTATIVA_2,
    CTE.DT_TENTATIVA_3,
    TO_CHAR(CTE.DT_CONTATO, 'YYYYMM') AS NR_DATA_CONTATO,
    CTE.DT_AGENDA,
--    CTE.CD_AGENDAMENTO,
    CTE.FG_RESTRICAO_IDADE,
    CTE.DS_RESTRICAO,
    CTE.FG_PRE_NATAL,
    CTE.FG_AGENDA_PARTICULAR,
    CTE.DT_CONSULTA_PARTICULAR,
    CTE.NR_VALOR_CONSULTA_PARTICULAR,
    CTE.FG_CHAMADO_MOVIDESK,
    CTE.NR_CHAMADO_MOVIDESK,
    DPL.NR_DIAS_ESPERA_PLANO,
    DPA.NR_DIAS_ESPERA_PARTICULAR,
    CTE.CD_UNIMED,
--    CTE.CD_CONTATO,
   CTE.CD_TENTATIVA,
    CTE.CD_ENDERECO
FROM CTE
    LEFT JOIN DIAS_PLANO DPL 
        ON DPL.CD_PRESTADOR = CTE.CD_PRESTADOR
       AND DPL.DT_CONTATO = CTE.DT_CONTATO
       AND DPL.DT_AGENDA = CTE.DT_AGENDA
    LEFT JOIN DIAS_PARTICULAR DPA 
        ON DPA.CD_PRESTADOR = CTE.CD_PRESTADOR
       AND DPA.DT_CONTATO = CTE.DT_CONTATO
       AND DPA.DT_CONSULTA_PARTICULAR = CTE.DT_CONSULTA_PARTICULAR