
version: 2
sources:
  - name : APP_GESTAO_REDE
    description: ESTAMOS UTILIZANDO O BANCO DE HOMOLOGAÇÃO E A TABELA APP_GESTAO_REDE
    tables:
      - name: ST_LISTAS_CLIENTE_OCULTO
        description: Essa tabela nos traz colunas com todas as listas pré definidas pela área
      - name: ST_CLIENTE_OCULTO
        decription: Tabela principal

models:
  - name: td_especialidade
    description: Tabela de especialidades
    columns:
      - name: CD_ESPECIALIDADE
        data_tests:
          - unique
          - not_null


